### ISSUE TITLE
we are so bored of see nothing in this repo

### ISSUE THREAD

**Issue by mzalaki00** [xg416/TMT#4]
when, exactly when do you want to put your claimed models!!? unless everything is fake

**Comment by xg416** [comment]
Hi, the models were released on 10/10 but removed on 10/16 by someone (with email address 516823499@qq.com) because I gave everyone the editor's permission! I've recovered those models.
It took over a year to make the paper accepted; we were constantly asked to make modifications by reviewers, and that's why the final version is so late.
